# Generated by Django 5.0.1 on 2024-01-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Адрес')),
                ('inn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'Торговая организация',
                'verbose_name_plural': 'Торговые организации',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название')),
                ('country', models.CharField(blank=True, default='Россия', max_length=5000, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ('-country', '-name'),
            },
        ),
        migrations.CreateModel(
            name='TradePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5000, verbose_name='Название')),
                ('type', models.IntegerField(choices=[(1, 'Киоск'), (5, 'Магазин'), (10, 'Универмаг')], default=5, verbose_name='Тип торговой точки')),
                ('address', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Адрес')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_points', to='organization.organization', verbose_name='Торговая организация')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('product_name', models.CharField(max_length=5000, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organization.supplier', verbose_name='Поставщик')),
                ('trade_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='organization.tradepoint', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Заказ поставщикам',
                'verbose_name_plural': 'Заказы поставщикам',
                'ordering': ('-product_name',),
            },
        ),
    ]
