# Generated by Django 5.0.1 on 2024-01-08 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1994, 1, 15, 11, 20, 46, 876672, tzinfo=datetime.timezone.utc), verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(1994, 1, 15, 11, 20, 46, 876672, tzinfo=datetime.timezone.utc), verbose_name='Дата рождения'),
        ),
    ]
